import { Item } from './types.ts';

export const sampleItems: Item[] = [
    {
        id: 1,
        type: 'section',
        record: { title: 'Section 1' },
        sortOrder: 0,
        path: [1],
    },
    {
        id: 2,
        type: 'item',
        record: { title: 'Item 1' },
        sortOrder: 0,
        path: [1, 2],
    },
    {
        id: 3,
        type: 'item',
        record: { title: 'Item 2' },
        sortOrder: 1,
        path: [1, 3],
    },
    {
        id: 4,
        type: 'section',
        record: { title: 'Section 2' },
        sortOrder: 1,
        path: [4],
    },
    {
        id: 5,
        type: 'item',
        record: { title: 'Item 3' },
        sortOrder: 0,
        path: [4, 5],
    },
    {
        id: 6,
        type: 'section',
        record: { title: 'Section 3' },
        sortOrder: 1,
        path: [4, 6],
    },
    {
        id: 7,
        type: 'item',
        record: { title: 'Item 4' },
        sortOrder: 0,
        path: [4, 6, 7],
    },
    {
        id: 8,
        type: 'item',
        record: { title: 'Item 5' },
        sortOrder: 1,
        path: [4, 6, 8],
    },
    {
        id: 9,
        type: 'section',
        record: { title: 'Section 4' },
        sortOrder: 2,
        path: [9],
    },
    {
        id: 10,
        type: 'item',
        record: { title: 'Item 6' },
        sortOrder: 0,
        path: [9, 10],
    },
    {
        id: 11,
        type: 'item',
        record: { title: 'Item 7' },
        sortOrder: 1,
        path: [9, 11],
    },
    {
        id: 12,
        type: 'item',
        record: { title: 'Item 8' },
        sortOrder: 2,
        path: [9, 12],
    },
    {
        id: 13,
        type: 'item',
        record: { title: 'Item 9' },
        sortOrder: 3,
        path: [9, 13],
    },
];
